IIIF/presentation-validator

requirements.txt, validator.py
Adds requirements.txt for:  pip install -r requirements.txt
And actually use iiif_prezi
State is still broken, due to contexts being unavailable.
=> Add requirements and use iiif_prezi

foot.html, head.html, index.html, validator.py
* This adds a `/` index route to the document.  
* It re-writes the header/footer to more reflect the current IIIF.io style, and it replaces all links with full URLs, not relative ones.
* It adds a small script that renders the HTML results inline via AJAX.
=> Added an index.html, and results are now shown on the page.

validator.py
Fix imports and `except` syntax.
=> Tweaks for python3 as well as python2

README.md, iiif-presentation-validator.py, requirements.txt
* rename script
* update dependency on iiif_prezi to 0.2.2 which includes contexts
* update README to omit context copying
* update script to expect HTML in same dir as script rather than cwd (should go away if HTML generation remove though)
=> Rename script and update dependency on iiif_prezi

iiif-presentation-validator.py, index.html
Now it always responds with JSON.
Lots of simplification of the code from this.
=> Removed the ability to request various formats from the validator.  

.travis.yml, iiif-presentation-validator.py, tests/test_validator.py
* Add a very simple test that will at least check that we stay OK with py2 and py3
* Clean cruft code: not_implemented() & error()
=> Trivial test for travis

iiif-presentation-validator.py
```
$ curl -X OPTIONS -I http://localhost:8080/validate
HTTP/1.0 200 OK
Date: Sat, 17 Dec 2016 17:14:23 GMT
Server: WSGIServer/0.1 Python/2.7.10
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET,POST,OPTIONS
Access-Control-Allow-Headers: Origin, Accept, Content-Type, X-Requested-With, X-CSRF-Token
Content-Length: 0
Allow: GET,POST,OPTIONS
Content-Type: text/html; charset=UTF-8
```bash
$ curl -X POST --data @../iiif-prezi/tests/testdata/2.0/example/fixtures/1/manifest.json \
http://localhost:8080/validate
```
```json
{"received":  "...", 
"error": "Expected version 2.1 context, got version 2.0", 
"okay": 0, 
"warnings": []}
```
(which is a different bug, but the CORS should be fixed.
=> Fix OPTIONS and POST w/o content-type header

iiif-presentation-validator.py
(Can rewrite history to squash commits later if anyone really cares)
=> Fix json encode/decode in Py3

.gitignore, .travis.yml, README.md, fixtures/1/manifest.json, fixtures/2/manifest.json, fixtures/README.md, iiif-presentation-validator.py, index.html, requirements.txt, setup.py, tests/test_validator.py
I've made a stab at tests for most of the validator though some of this is a bit klunky because of awkwardness of mocking Bottle and structure of validator code. Also adds coverage via coveralls
=> Some tests and a few more fixes

fixtures/3/broken_choice.json, fixtures/3/choice.json, schema/iiif_3_0.json, tests/test_validator.py
implement choice on body
enforce (width, height) or duration on canvas
=> Choice and canvas duration/width,height enforcement

fixtures/3/broken_embedded_annos.json, schema/iiif_3_0.json, schema/schemavalidator.py, tests/test_validator.py
In the light of:
https://github.com/IIIF/cookbook-recipes/pull/130
This pull requests enforces `AnnotationPage` to only contain `id`,`type` and `items`.
=> Tightening up definition of AnnotationPage

fixtures/3/annoPageMultipleMotivations.json, schema/iiif_3_0.json, tests/test_validator.py
Fixes https://github.com/IIIF/presentation-validator/issues/85
=> Allowing motivation to be an array

setup.py
Sticking bottle to version 6.2.2 or less for python 2
=> Fixing python 2.7 build

.travis.yml, iiif-presentation-validator.py, tests/test_validator.py
Show in interface rather than hiding
=> Surface HTTP errors

fixtures/3/extension_anno.json, schema/error_processor.py, schema/iiif_3_0.json, tests/test_validator.py
=> Being less opinionated about Annotation body types

iiif-presentation-validator.py, index.html, schema/error_processor.py, setup.py
Adds better error handling so 500 errors are shown in the website
Fixes 500 error for this instance
Added Javascript to change the text so its possible to see if the validator is working
=> Fixes #104 2.0 manifest throws 500 error

schema/error_processor.py, setup.py
Fixing bug where validation errors for manifests with over 10 pages failed.
Fixes #107
=> Fixing 10 page bug

.travis.yml, iiif-presentation-validator.py, tests/test_validator.py
As requested on Slack:
https://iiif.slack.com/archives/C18FHBKAQ/p1607588021184700
=> Adding check to see if manifest id matches the published location

.travis.yml, schema/iiif_3_0.json, setup.py, tests/test_validator.py
=> Fix 3.0 id manifest validation

fixtures/3/full_example.json, schema/iiif_3_0.json
=> Logo only allowed on provider #144

schema/iiif_3_0.json
Fixes: https://github.com/iiif-prezi/iiif-prezi3/issues/126
and adds rendering where it is allowed according to:
https://iiif.io/api/presentation/3.0/#a-summary-of-property-requirements
=> Adding rendering where it is allowed

.github/workflows/test.yml, schema/iiif_3_0.json, tests/test_validator.py
=> Expanding definition for target source

.github/workflows/test.yml, fixtures/3/annoPageInCollection.json, schema/iiif_3_0.json, schema/schemavalidator.py, setup.py, tests/test_validator.py
=> Supporting linked annotation collections

fixtures/3/anno_source.json, schema/iiif_3_0.json
Moving https://github.com/IIIF/presentation-validator/pull/180 locally to run tests
=> Make selector on SpecificResource optional.

schema/iiif_3_0.json
for Manifest, Collection, AnnotationPage, AnnotationCollection and Range. Basically anything that could be a reference. 
Should fix: https://github.com/iiif-prezi/iiif-prezi3/issues/122
=> Requiring items 

schema/iiif_3_0.json
Fixes https://github.com/iiif-prezi/iiif-prezi3/issues/255
=> Adding behavior to range
