- implementations/manifest-factory/factory.py
I discovered this while using `build-from-directory.py`, which calls `add_image_annotation`.
> Fixed: calling add_image_annotation results in infinite recursion

- implementations/validator/validator.py
This ensures that the validator cannot be exploited if someone finds a creative way to leak information from something like `file:///etc/passwd`.
> Validator: require HTTP URLs

- implementations/validator/validator.py
Add argparse to allow the default host and port to be configured using `--hostname` and `--port`
* Added simple docstring to serve as the intro for `--help` output
> validator: use argparse for customization

- implementations/validator/validator.py
New "/postvalidate" route receives POST of JSON body-text with a Content-Type:application/json. Responds with JSON returning the received data, an okay flag, warnings, and errors.
> added /postvalidate route for JSON POST validation

- .gitignore
- tests/test_validator.py
won't have to copy /contexts in anymore so no need to exclude
> No longer need to ignore contexts as included in iiif-prezi package

- .ebextensions/packages.config
- .ebextensions/pip.config
- .ebextensions/wsgi.config
- .travis.yml
These changes are a portion of the work needed to simplify the splitting of repos for iiif.io:
- the `.ebextensions` stuff is to be able to deploy this as a standalone service in AWS in ElasticBeanstalk
- the `.travis.yml` stuff ships a copy of the code to S3 so we can auto-deploy this to said ElasticBeanstalk environment
oh, and the secret key in `.travis.yml` is encrypted :)
> Adds deployment stuff for AWS

- .travis.yml
Apparently each repository requires their own key
> Fix travis encrypted AWS credentials

- iiif-presentation-validator.py
I believe this is causing the following to fail:
http://presentation-validator.iiif.io/
due to the following error in the log:
```
which: no identify in (/opt/python/run/venv/bin/:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/sbin:/sbin:/bin)
[Fri Aug 25 01:10:24.015160 2017] [:error] [pid 7012] [remote 172.31.86.71:58080] Traceback (most recent call last):
[Fri Aug 25 01:10:24.015189 2017] [:error] [pid 7012] [remote 172.31.86.71:58080]   File "/opt/python/run/venv/lib/python3.4/site-packages/bottle.py", line 862, in _handle
[Fri Aug 25 01:10:24.015193 2017] [:error] [pid 7012] [remote 172.31.86.71:58080]     return route.call(**args)
[Fri Aug 25 01:10:24.015196 2017] [:error] [pid 7012] [remote 172.31.86.71:58080]   File "/opt/python/run/venv/lib/python3.4/site-packages/bottle.py", line …
```
> Reading in index.html as a uft-8 file

- .gitignore
Replaces IIIF/presentation-validator#50 with something on a branch that doesn't trigger travis deploy failure for py3.4... I hope
> Extra ignores for pyc and egg-info

- iiif-presentation-validator.py
As per [the recent Slack conversation](https://iiif.slack.com/archives/C1C3N4TS4/p1515164327000697) this change requets gzip transfer compression and warns when it is not supported or when the server supports it but does not set the Vary header correctly.
(Obviously, if accepted this should be ported to the image-validator as well)
> Add transfer compression warnings

- .gitignore
- .travis.yml
- iiif-presentation-validator.py
- tests/test_validator.py
I noticed while looking into https://github.com/IIIF/iiif.io/issues/1142 I noticed that the validator output had:
> Validation Results:
>
> URL Tested: None
where it should have shown the URL being tested. Seems that this had been broken between the current live version and the current master. This PR fixes that so should be merged before the live version is updated.
Also tidied http/https test, fixed test setup for mocking requests, and some tidy. Added py3.6 to travis tests too.
> URL return and tests

- schema/iiif_3_0.json
The value must be a positive floating point number.
> fix duration

- fixtures/3/collection.json
- fixtures/3/collection_of_collections.json
- fixtures/3/full_example.json
- schema/iiif_3_0.json
- tests/test_validator.py
Hi, 
I don't know a lot about JSON schema so there may be a better way than what I did.  
1.  I added 2 fixture files with examples of collections with manifests and a collection with sub-collections and then manifests.  Which I added to the tests section.  
2.  I added additional classes for a manifest and a collection similar to the canvas one but without the height and width validation.  If there is another way in jsonschema to do a conditional check based on the type these classes may not be necessary.  
3.  I then used those classes as a oneof property in the items section of the "top-level" pattern.
> updated the jsonschema to add some collection validation for iiif 3.

- iiif-presentation-validator.py
- setup.py
Adds a User-Agent request header for services (like Cloudflare) that reject traffic that doesn't identify itself.
Bumps semantic version to `0.0.3`
#92
> Add User-Agent to request header

- fixtures/3/broken_service.json
- iiif-presentation-validator.py
- requirements.txt
- schema/error_processor.py
- schema/schemavalidator.py
- setup.py
- tests/test_validator.py
Given a schema error that ends in `oneOf` expression the current json schema library will check all possibilities in a `oneOf` clause and return validation error messages for each one
These changes will identify the real `oneOf` that causes the error by checking the type of each `oneOf` possibility and returning only the one that matches.
> Improve debug messages

- schema/iiif_3_0.json
I noticed a typo in the schema when using the online validator. Should I also open an issue when correcting a typo?
Thanks for the work on IIIF!
> typo languagae -> language in 3.0 json schema

- fixtures/3/non_cc_license.json
- fixtures/3/old_cc_license.json
- fixtures/3/rightsstatement_license.json
- schema/iiif_3_0.json
- tests/test_validator.py
Allow different versions of creative commons license statement while retaining a test to ensure the following:
https://iiif.io/api/presentation/3.0/#rights
"The value must be drawn from the set of Creative Commons license URIs, the RightsStatements.org rights statement URIs"
> Loosening the test for valid license URIs

- fixtures/3/old_format_label.json
- schema/error_processor.py
- schema/iiif_3_0.json
- schema/schemavalidator.py
- setup.py
- tests/test_validator.py
A number of issues here. The error finder seemed to struggle when the error was in the root.
Also decided to limit the allowable fields in the manifest to catch old fields like sequence
Fixes https://github.com/IIIF/presentation-validator/issues/97
> Fixing issue that causes the 500 error

- iiif-presentation-validator.py
- requirements.txt
- setup.py
Using requests JSON-LD document loader as current iiif-prezi
document loaded isn't working with latest pyld due to missing
parameters in the method.
> Fixing 2.0 validation

- fixtures/3/multi_bodies.json
- iiif-presentation-validator.py
- schema/error_processor.py
- schema/iiif_3_0.json
- tests/test_validator.py
Discovered through Cookbook: https://github.com/IIIF/cookbook-recipes/pull/223
> Fixing issue where multiple bodies in an annotation caused validation to fail.

- schema/iiif_3_0.json
As per: https://iiif.io/api/presentation/3.0/#table-reqs-3 Manifests and Collections may have a `services` property containing an array of services.
> Added missing services property to validator

- schema/iiif_3_0.json
This pull request add [the default keywords to the JSON shema](http://json-schema.org/understanding-json-schema/reference/generic.html) for the main IIIF object classes.
E.g. the default keyword for Manifest type is "Manifest".
The default keywords are useful for solving https://github.com/iiif-prezi/iiif-prezi3/issues/12.
> Add default keyword values for main IIIF objects

- iiif-presentation-validator.py
Relates to #139. When a KeyError exception occurs there is no feedback apart from printing '0'. Maybe could return a better error message as well.
> Improving debug in case of failure

- fixtures/3/collection_of_canvases.json
- fixtures/3/range_range.json
- iiif-presentation-validator.py
- schema/error_processor.py
- schema/iiif_3_0.json
- tests/test_validator.py
> iiif-prezi fixes

- fixtures/3/accompanyingCanvas.json
- fixtures/3/placeholderCanvas.json
- schema/iiif_3_0.json
- tests/test_validator.py
Should fix:
https://github.com/iiif-prezi/iiif-prezi3/issues/125
and
https://github.com/iiif-prezi/iiif-prezi3/issues/124
I've created two new types and copied a lot of the properties from canvas to ensure there isn't a circular reference. This will mean extra maintenance.
> Adding specific support for accompanyingCanvas and placeholderCanvas

- iiif-presentation-validator.py
- index.html
- tests/test_validator.py
For IIIF services that provide both v2 and v3 manifests at the same URL, the validator needs to send an appropriate 'accept' header to ensure it is returning the appropriate IIIF version response.
This PR adds a checkbox to the validator to optionally include an 'Accept' header in the request. The header is set according to the selected IIIF version, which makes it possible to request v3 manifests from a 'default' v2 service, or vice-versa.
> New: Add 'accept' header option on validator
